# appveyor.yml
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - gem install bundler
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec
  - bundle exec ruby -Ilib bin/metric_fu --no-open
